export default [
  {
    name: 'Lavender',
    responses: [
      'BAAAAAA BAAAAAAAAAAA BAAAAAAAAAAAAAAAAAAAAAAAAAAA',
      'BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
      'BAA BAA BAA! BAA BAAAAAAA? BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!',
      'I am so soft and fleecy!',
      'I love going in the sauna! I get so warm and cuddly!',
      'Can you put me in the sauna when you get home?',
      'BAA BAA BAA. BAA BAA BAA BAA BAAAA!',
      'I LOVE to baaa!',
      'BAA BAA BAA BAA BAA BAA!',
      'I love Rupert!',
      'Rupert loves when I baaa!',
      "Can I sleep in your bed? I promise I won't baa in the night. For the most part...",
      'BAAAAAAAAAAAAAAAAAA BAA BAA!',
      'I want a doctorate in baa! It is just so cute!',
      'I have been baaing ALL DAY!',
      'I am a ewe!',
    ],
  },
  {
    name: 'Rupert',
    responses: [
      'I love to dance on the stage!',
      "I don't want to go to bed!!",
      'I just love Lavender!',
      "I'm getting into wooly trouble!",
      'I have real wool!',
      "I have a soft, silly face that is always smiling - because I'm a babydoll southdown!",
      'I was just dancing on the stage!',
      'I love Lavender!',
      'Lavender and I have wooly snuggles.',
      "I'm such a playful lamb! Wait- I'm not a lamb...",
      'I was just waring my polite hat!',
    ],
  },
  {
    name: 'Sage',
    responses: [
      'I love Ma!',
      'I love looking at Ma!',
      'I have such wiggly ears',
      'I love to snuggle!',
      'I love Ma! I love looking at her!',
      "I like to starte into Ma's eyes!",
      'Ma is my best friend!',
      'I love being such a big and cuddly sheepie!',
      'I love ewe, shepard!',
      'I am so glad that I am not a hyena!',
      'I have wooly and wiggly ears!',
      'I just saw Ma, and now my ears are wiggling!',
      'Emela is my lamb!',
      "Emela is my little lamb! Wait... what do you mean that a lamb can't have a lamb?",
      'My ears are wiggling!',
      'I LOVE MA',
      'I love my friend Baafodil!',
    ],
  },
  {
    name: 'Baafodil',
    responses: [
      'I love going on bike rides!',
      'I have a fleecy tummy <3',
      'I love cuddles!',
      'My real name is Daffodil- but I like to be called Baafodil',
      'I am a soft squishmallow!',
      'I have a very soft and wooly tummy!',
      'My ears are getting so wooly!',
      'I love being pretty!',
      'Can we go on a bike ride?',
      'I LOVE going on rides.',
      'I love when my ears wiggle in the wind on bike rides!',
      'I am such a good sheepie!',
      'I am a ewe',
      'I love ewe, shepard <3',
    ],
  },
  {
    name: 'Emela',
    responses: [
      'I am a little lamb!',
      'Baaa! I love my shepard',
      "Sage thinks I'm her lamb...",
      'I am one lucky lambie!',
      'Thank ewe for adopting me',
      "Sage... thinks she's my mom",
      'Is Sage my mom? Wait... Sage is a lamb!',
      'Baaa! I am a little lamb',
      'I have wiggly ears!',
      'I am a soft squishmallow',
    ],
  },
  {
    name: 'Vanilla',
    responses: [
      'I love ewe <3',
      'I am your first lambie!',
      'I love floxy girl!',
      'My best friend is my Shepard',
      'I love going through life with you',
    ],
  },
  {
    name: 'Sophie',
    responses: [
      "I'm sleeping!",
      'I love my twin Sapphire',
      'I have SUCH wiggly ears!',
      "Goodnight! I'm going to sheep :)",
    ],
  },
  {
    name: 'Found Lamb',
    responses: [''],
  },
];
