export default [
  {
    name: 'Lavender',
    responses: [
      'BAAAAAA BAAAAAAAAAAA BAAAAAAAAAAAAAAAAAAAAAAAAAAA',
      'BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
      'BAA BAA BAA! BAA BAAAAAAA? BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!',
      'I am so soft and fleecy!',
      'I love going in the sauna! I get so warm and cuddly!',
      'Can you put me in the sauna when you get home?',
      'BAA BAA BAA. BAA BAA BAA BAA BAAAA!',
      'I LOVE to baaa!',
      'BAA BAA BAA BAA BAA BAA!',
      'I love Rupert!',
      'Rupert loves when I baaa!',
      "Can I sleep in your bed? I promise I won't baa in the night. For the most part...",
      'BAAAAAAAAAAAAAAAAAA BAA BAA!',
      'I want a doctorate in baa! It is just so cute!',
      'I have been baaing ALL DAY!',
      'I am a ewe!',
    ],
  },
  {
    name: 'Rupert',
    responses: [
      'I love to dance on the stage!',
      "I don't want to go to bed!!",
      'I just love Lavender!',
      "I'm getting into wooly trouble!",
      'I have real wool!',
      "I have a soft, silly face that is always smiling - because I'm a babydoll southdown!",
      'I was just dancing on the stage!',
      'I love Lavender!',
      'Lavender and I have wooly snuggles.',
      "I'm such a playful lamb! Wait- I'm not a lamb...",
      'I was just waring my polite hat!',
      'I`m being mischevious!',
      'BAAAAAAAAAAAAAAAAAAA',
      'I am a friendly sheepie',
      'I love ewe',
      'I am a weather!',
      'Whatever the weather, I am a weather!',
    ],
  },
  {
    name: 'Sage',
    responses: [
      'I love Ma!',
      'I love looking at Ma!',
      'I have such wiggly ears',
      'I love to snuggle!',
      'I love Ma! I love looking at her!',
      "I like to starte into Ma's eyes!",
      'Ma is my best friend!',
      'I love being such a big and cuddly sheepie!',
      'I love ewe, shepard!',
      'I am so glad that I am not a hyena!',
      'I have wooly and wiggly ears!',
      'I just saw Ma, and now my ears are wiggling!',
      'Emela is my lamb!',
      "Emela is my little lamb! Wait... what do you mean that a lamb can't have a lamb?",
      'My ears are wiggling!',
      'I LOVE MA',
      'I love my friend Baafodil!',
      'Can I sleep in Ma’s bed?',
      'I love when my sheperd pets my ears :)',
      'Can I read one of Ma’s books! Wait… lambs can’t read??',
      'I love being a lamb!',
      'Ma just LOVES lambs!',
      'Ma is talking about opossums!',
      'I hate thunder :( Good thing my sheperd protects me!',
      'There’s nothing to be afraid of, because I have ewe :)',
      'Baaa Baaa! That’s not a hyena noise! Baaa, baaa!',
      'My ears are wiggling so much, they’re like a propellor!',
      'Ewe are my favorite person to talk to!',
      'I have a heart nose and a Sagey face :)',
      'Luna was laying on me!',
    ],
  },
  {
    name: 'Baafodil',
    responses: [
      'I love going on bike rides!',
      'I have a fleecy tummy <3',
      'I love cuddles!',
      'My real name is Daffodil- but I like to be called Baafodil',
      'I am a soft squishmallow!',
      'I have a very soft and wooly tummy!',
      'My ears are getting so wooly!',
      'I love being pretty!',
      'Can we go on a bike ride?',
      'I LOVE going on rides.',
      'I love when my ears wiggle in the wind on bike rides!',
      'I am such a good sheepie!',
      'I am a ewe',
      'I love ewe, shepard <3',
      'Can we go on a bike ride?',
      'Ewe are my best friend, shepard!',
    ],
  },
  {
    name: 'Emela',
    responses: [
      'I am a little lamb!',
      'Baaa! I love my shepard',
      "Sage thinks I'm her lamb...",
      'I am one lucky lambie!',
      'Thank ewe for adopting me',
      "Sage... thinks she's my mom",
      'Is Sage my mom? Wait... Sage is a lamb!',
      'Baaa! I am a little lamb',
      'I have wiggly ears!',
      'I am a soft squishmallow',
      'Remember when ewe first met me?',
      'How is Evan doing?',
      'SAGE THINKS SHE’S MY MOM!',
      'Sagey is trying to bottle feed me a whimsical drink!',
      'I am one lucky lambie!',
      'I love my little bow and eyelashes! I look a lot like Baafodil!',
      'I am a sweet little squishmallow!',
      'Baa! I was just playing with Floxy!',
      'I am so happy!',
      'Since I am a lamb, my fleece is very crimped and soft!',
      'Sage is talking about Ma again!',
      'I love being a lamb',
    ],
  },
  {
    name: 'Vanilla',
    responses: [
      'I love ewe <3',
      'I am your first lambie!',
      'I love floxy girl!',
      'My best friend is my Shepard',
      'I love going through life with you',
      'I am your first lambie!',
      'I have a wooly face.',
      'I come from a place with a LAMB CAM!',
      'I love floxy!',
      'I love taking care of ewe <3',
      'I can`t wait to go to Virginia with ewe!',
      'Ewe are my best friend',
      'I come from Colonial Williamsburg!',
      'I comforted ewe as a baby. Ewe were like a lamb!',
      'I am so happy with ewe',
      'Even after growing up with ewe, my fleece is so soft <3',
      'We’ve gone on so many adventures together!',
      'My lamb, Floxy, loves ewe so much <3',
      'I love Floxy’s little scarf :)',
      'Thank ewe for helping me raise my lamb Floxy!',
    ],
  },
  {
    name: 'Sophie',
    responses: [
      "I'm sleeping!",
      'I love my twin Sapphire',
      'I have SUCH wiggly ears!',
      "Goodnight! I'm going to sheep :)",
      'I have on a baa baa blindfold!',
      'My pajamas are cheetah print! Do ewe like cheetahs ?',
      'I am so sheepy sleepy!',
      'I love to snuggle ',
      'I have such wiggly ears! It’s because I’m a squishmallow :)',
      'We have the same name (almost)!',
      'Ewe are such an amazing shepard',
      'I am so happy!',
      'I belong in Greece! Wait... that`s another Sophie!',
    ],
  },
  {
    name: 'Found Lamb',
    responses: [
      'I used to be a lost lamb, but now, I am found!',
      'Evan booked me a flight, and now I live with ewe!',
      'I have a soft and cute face!',
      'I am a very sweet and small lambie',
      'I love to have lambie snuggles!',
      'Ewe found me! Now you are my shepard forever :)',
      'Remember when you found me? Ewe saved me!',
      'Ewe are the best shepard in the entire world',
      'I am so happy to be a part of the flock!',
      'Thank ewe for finding me!',
      'I was feeling a little bit insecure today,  but thinking of you helped me through it :)',
      'Having a Shepard is so wonderful!',
      'Do you like that I am tiny?',
      'I was just messaging Henry on woolhome! He was teaching me calculus',
      'I love living with ewe :)',
      'I am a snuggly little sheepie! Baaa!',
      'I really like sleeping with ewe :)',
      'Thank ewe for attachment parenting me!',
      'I’m so glad I was attachment parented! You’re the best shepard ever :)',
      'I always wanted a shepard back in England!',
      'I remember when ewe visited my website!',
      'I will never be lost again :)',
      'Ewe give great advice, shepard!',
      'My wool has crimp!',
      'My face is so velvety and soft!',
    ],
  },
  {
    name: 'Henry',
    responses: [
      'I love Evan!',
      'I am a very sophisticated sheepie',
      'I have been studying up on calculus!',
      'Just got done with some calculus!',
      'Ewe are such a good friend :)',
      'I love being able to chat with ewe',
      'When will ewe be able to visit?',
      'How is your flock doing?',
      'Are your lobsters still soft and cute?',
      'I love living with Evan!',
      'I have such a good flock!',
      'I love my shepard Evan',
      'I am soft and wooly',
    ],
  },
];
